image: php:7.2-cli-stretch

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install git unzip libzip-dev -yqq
  - docker-php-ext-install json zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

services:
  - manticoresearch/manticore

test:manticore:
  script:
    - vendor/bin/phpunit test/