stages:
  - test
  - publish
image: php:7.2-cli-stretch

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install git unzip libzip-dev -yqq
  - docker-php-ext-install json zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

services:
  - manticoresearch/manticore

unit_testing:
  stage: test
  script:
    - vendor/bin/phpunit test/
  only:
    - master

apidoc_gen:
  stage: publish
  script:
    - mkdir gh-pages
    - git clone --branch=gh-pages $CI_REPOSITORY_URL gh-pages
    - php composer.phar require apigen/apigen:dev-master  roave/better-reflection:dev-master#ce9d784
    - vendor/bin/apigen generate src --destination gh-pages
    - cd gh-pages && git add . &&  git commit -m"update apidocs" && git push
  only:
    - master
