title: Manticore Search PHP Client
remote_theme: pmarsceill/just-the-docs
search_enabled: false
footer_content: "Copyright &copy; 2020 Manticore Search Ltd."
heading_anchors: true
aux_links:
  "API docs":
    - "api"
  "Manticore Search":
    - "//github.com/manticoresoftware/manticoresearch"

